service: sleep-time-logging

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  region: ap-northeast-1

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  bedtime:
    handler: bin/bedtime-delay
    events:
      - http:
          path: bedtime
          method: post
    environment:
      TZ: Asia/Tokyo
      PIXELA_USER: <user-id>
      PIXELA_TOKEN: <your-token>
      PIXELA_GRAPH: <your-graph-id-1>
  wakeup:
    handler: bin/wakeup-delay
    events:
      - http:
          path: wakeup
          method: post
    environment:
      TZ: Asia/Tokyo
      PIXELA_USER: <user-id>
      PIXELA_TOKEN: <your-token>
      PIXELA_GRAPH: <your-graph-id-1>
  hello:
    handler: bin/hello
    events:
      - http:
          path: hello
          method: post